### ISSUE TITLE
problems of apps_plus dataset

### ISSUE THREAD

**Issue by binglinchengxiash** [Ablustrund/APPS_Plus#3]
Has the dataset been divided into training and testing?

**Comment by Ablustrund** [comment]
Sure! We randomly select parts of samples in each category to construct the dev and test set. We will provide the datasets in the later.

**Comment by binglinchengxiash** [comment]
> Sure! We randomly select parts of samples in each category to construct the dev and test set. We will provide the datasets in the later.

**Comment by renhouxing** [comment]
@Ablustrund Hi, could you please share the details of your data splitting?
