### ISSUE TITLE
For StepCoder, does the algorithm only work given a canonical solution

### ISSUE THREAD

**Issue by frasermince** [Ablustrund/APPS_Plus#4]
Looking over your recent paper I was curious how the algorithm works at inference. I understand you are breaking down each coding problem into a code completion problem using the canonical solution and relying less upon this solution as the algorithm progresses. However I do not quite understand how this works at inference time when no canonical solution is provided. Apologies if this is not directly related to APPS Plus but I would love some clarity on this point.

**Comment by Ablustrund** [comment]
Thank you for your attention.
The optimization objective at the end of training is the same as at inference time, we only need to enable the model to generate the response (i.e., code) given the human description.

**Comment by frasermince** [comment]
Thanks for the info! So does that mean that for inference you just have llm generation follow the policy from the training process without using inference compiler/unit test outputs?

**Comment by Ablustrund** [comment]
> Thanks for the info! So does that mean that for inference you just have llm generation follow the policy from the training process without using inference compiler/unit test outputs?

You are right. In the inference time, the policy model can generate the code according the human requirements, without any feedback by using compiler output.
