### ISSUE TITLE
Hi! If there is an update on when the code will be released?

### ISSUE THREAD

**Issue by Anna7355** [Ablustrund/APPS_Plus#7]

**Comment by Ablustrund** [comment]
Hi, sure.
👉 08/31/2024. We clean the function name of the canonical solution in each programming problem. The final version of our APPS+ dataset is available at here: https://drive.usercontent.google.com/download?id=1dTRJHXhMcPz4CPt73f2vju5KdLmqcP4F&export=download&authuser=0
